version: '1.0'
stages:
 - clone
 - build
 - test
 - push
 - release
steps:
  clone:
    title: "Cloning main repository..."
    stage: "clone"
    type: "git-clone"
    arguments:
      repo: "codefresh-contrib/heroku-python-django-sample-app"
      revision: "master"
      git: "github"
  build:
    title: "Building Docker Image..."
    stage: "build"
    type: "build"
    working_directory: "./heroku-python-django-sample-app"
    arguments: 
      image_name: "${{IMAGE_NAME}}"
      tag: "master"
      dockerfile: "Dockerfile"
  run_unit_tests:
     title: "Running unit tests..."
     stage: "test"
     type: "freestyle"
     working_directory: "./heroku-python-django-sample-app"
     arguments:
       image: '${{build}}'
       commands:
         - "python -m unittest composeexample.utils"
  push_image:
    title: "Pushing image to Heroku..."
    stage: "push"
    type: "push"
    arguments:
      candidate: '${{build}}'
      image_name: "${{IMAGE_NAME}}/web"
      registry: "heroku"
  release_image:
    title: "Releasing image..."
    stage: "release"
    type: "freestyle"
    arguments:
      image: "nazarcodefresh/heroku-cli:alpine"
      commands:
        - >-
          printf "machine api.heroku.com\n  login $EMAIL\n  password
          $API_TOKEN\nmachine git.heroku.com\n  login $EMAIL\n  password
          $API_TOKEN\n" > ~/.netrc
        - "heroku container:release --app $IMAGE_NAME web"
    
